AllCops:
  Exclude:
    - db/schema.rb
    - ./bin/**/*
  RunRailsCops: true
Documentation:
  Enabled: false
Metrics/AbcSize:
  Exclude:
    - ./**/db/**/*.rb
Metrics/LineLength:
  Exclude:
    - Guardfile
    - ./**/initializers/devise.rb
  Max: 120
Metrics/MethodLength:
  Exclude:
    - ./**/db/**/*.rb
Style/ClassAndModuleChildren:
  Exclude:
    - ./**/app/**/*.rb
    - ./**/spec/**/*.rb